// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrustIdentity.Storage.EntityFramework;

#nullable disable

namespace TrustIdentity.Storage.Migrations.UserDb
{
    [DbContext(typeof(TrustIdentityDbContext))]
    [Migration("20260122103738_InitialUserDbMigration")]
    partial class InitialUserDbMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("TrustIdentity.Core.Models.TrustIdentityUser", b =>
                {
                    b.Property<string>("SubjectId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberVerified")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Roles")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("SubjectId");

                    b.HasIndex("Email");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TrustIdentity.Core.Models.UserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Issuer")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrustIdentityUserSubjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ValueType")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TrustIdentityUserSubjectId");

                    b.ToTable("UserClaim");
                });

            modelBuilder.Entity("TrustIdentity.Core.Models.TrustIdentityUser", b =>
                {
                    b.OwnsOne("TrustIdentity.Core.Models.UserAIProfile", "AIProfile", b1 =>
                        {
                            b1.Property<string>("TrustIdentityUserSubjectId")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("LastRiskAssessment")
                                .HasColumnType("TEXT");

                            b1.Property<double>("RiskScore")
                                .HasColumnType("REAL");

                            b1.Property<double>("TrustScore")
                                .HasColumnType("REAL");

                            b1.HasKey("TrustIdentityUserSubjectId");

                            b1.ToTable("Users");

                            b1.ToJson("AIProfile");

                            b1.WithOwner()
                                .HasForeignKey("TrustIdentityUserSubjectId");

                            b1.OwnsMany("TrustIdentity.Core.Models.BehaviorPattern", "BehaviorPatterns", b2 =>
                                {
                                    b2.Property<string>("UserAIProfileTrustIdentityUserSubjectId")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate()
                                        .HasColumnType("INTEGER");

                                    b2.Property<double>("Confidence")
                                        .HasColumnType("REAL");

                                    b2.Property<string>("PatternType")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.HasKey("UserAIProfileTrustIdentityUserSubjectId", "__synthesizedOrdinal");

                                    b2.ToTable("Users");

                                    b2.WithOwner()
                                        .HasForeignKey("UserAIProfileTrustIdentityUserSubjectId");
                                });

                            b1.OwnsMany("TrustIdentity.Core.Models.DeviceFingerprint", "KnownDevices", b2 =>
                                {
                                    b2.Property<string>("UserAIProfileTrustIdentityUserSubjectId")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate()
                                        .HasColumnType("INTEGER");

                                    b2.Property<DateTime>("FirstSeen")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Id")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("IpAddress")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<bool>("IsTrusted")
                                        .HasColumnType("INTEGER");

                                    b2.Property<DateTime>("LastSeen")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Location")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("UserAgent")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.HasKey("UserAIProfileTrustIdentityUserSubjectId", "__synthesizedOrdinal");

                                    b2.ToTable("Users");

                                    b2.WithOwner()
                                        .HasForeignKey("UserAIProfileTrustIdentityUserSubjectId");
                                });

                            b1.OwnsMany("TrustIdentity.Core.Models.LoginAttempt", "RecentLogins", b2 =>
                                {
                                    b2.Property<string>("UserAIProfileTrustIdentityUserSubjectId")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate()
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("IpAddress")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Location")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Reason")
                                        .HasColumnType("TEXT");

                                    b2.Property<double>("RiskScore")
                                        .HasColumnType("REAL");

                                    b2.Property<bool>("Success")
                                        .HasColumnType("INTEGER");

                                    b2.Property<DateTime>("Timestamp")
                                        .HasColumnType("TEXT");

                                    b2.HasKey("UserAIProfileTrustIdentityUserSubjectId", "__synthesizedOrdinal");

                                    b2.ToTable("Users");

                                    b2.WithOwner()
                                        .HasForeignKey("UserAIProfileTrustIdentityUserSubjectId");
                                });

                            b1.Navigation("BehaviorPatterns");

                            b1.Navigation("KnownDevices");

                            b1.Navigation("RecentLogins");
                        });

                    b.Navigation("AIProfile");
                });

            modelBuilder.Entity("TrustIdentity.Core.Models.UserClaim", b =>
                {
                    b.HasOne("TrustIdentity.Core.Models.TrustIdentityUser", null)
                        .WithMany("Claims")
                        .HasForeignKey("TrustIdentityUserSubjectId");
                });

            modelBuilder.Entity("TrustIdentity.Core.Models.TrustIdentityUser", b =>
                {
                    b.Navigation("Claims");
                });
#pragma warning restore 612, 618
        }
    }
}
