<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PackageId>TrustIdentity.AspNetCore</PackageId>
    <Description>The ASP.NET Core integration for TrustIdentity server.</Description>
    <Authors>TrustIdentity Team</Authors>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="README.md" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="README.md">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../TrustIdentity.Abstractions/TrustIdentity.Abstractions.csproj" />
    <ProjectReference Include="../TrustIdentity.Core/TrustIdentity.Core.csproj" />
    <ProjectReference Include="../TrustIdentity.AI/TrustIdentity.AI.csproj" />
    <ProjectReference Include="../TrustIdentity.Saml/TrustIdentity.Saml.csproj" />
    <ProjectReference Include="../TrustIdentity.Storage/TrustIdentity.Storage.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>