<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TrustIdentity.Core" Version="1.0.0" />
    <PackageReference Include="TrustIdentity.UI" Version="1.0.0" />
  </ItemGroup>

</Project>
